version: '3.8'
services:
  db:
    image: "postgres"
    container_name: "postgresdb"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./sql/make_table.sql:/docker-entrypoint-initdb.d/init.sql